#!/usr/bin/env bash

## Project to build
project=$1
echo "Building $IMAGES for project $project ..."

## Sync src from development machine to nano
echo "Synching from devlopment machine to nano for project $project ..."
rsync -rlptza --delete --exclude=host -P src/ build@nano-one.local:~/$project

## Sync CUDA apt repositories on host into Docker build context for later bind-mounting
ssh build@nano-one.local << EOF
  mkdir ~/$project/host/ ||  true
  echo 'Synching files for local CUDA apt repo...'
  rsync -aq /var/cuda-repo-10-0-local-10.0.326/ ~/$project/host/cuda-repo

  echo 'Synching files for local CUDA ml apt repo...'
  rsync -aq /var/cuda-ml-local-repo/ ~/$project/host/cuda-ml-repo

  echo 'Exporting repo keys...'
  export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
  apt-key exportall > ~/$project/host/apt-trusted-keys
EOF

## Deactivate reference to plain http Docker registry mirror in cluster as buildkit does not support it - see https://github.com/moby/moby/issues/38303
ssh build@nano-one.local << EOF
  echo "Deactivating reference to plain http Docker registry mirror in cluster for $project ..."
  sudo su
  cp -f /etc/docker/daemon.json /etc/docker/daemon.json.orig
  echo "{ \"labels\": [ \"os=linux\", \"arch=arm64\" ], \"experimental\": true }" > /etc/docker/daemon.json
  service docker restart
  sleep 5
EOF

## Build Docker image on nano - using buildkit with experimental features to be able to bind-mount in Dockerfile
ssh build@nano-one.local << EOF
  echo "Building Docker image on nano for project $project ..."
  DOCKER_BUILDKIT=1 docker build -t $project ~/$project
EOF

## Reactivate original Docker configuration to allow pushing private Docker registry in cluster
ssh build@nano-one.local << EOF
  echo "Reactivating original Docker configuration for $project ..."
  sudo su
  cp -f /etc/docker/daemon.json.orig /etc/docker/daemon.json
  service docker restart
  sleep 5
EOF

## Tag and possibly push images
for image in $(echo $IMAGES | tr " " "\n")
do
    echo "Tagging as $image for project $project..."
    ssh build@nano-one.local "docker tag $project $image"
    if $PUSH_IMAGE
    then
        echo "Pushing $image for project $project..."
        ssh build@nano-one.local "docker push $image"
    fi
done
