#!/usr/bin/env bash

# Regular remote builder

## Project to build
project=$1

## Jetson model
if [[ -z "${JETSON_MODEL}" ]]; then
  JETSON_MODEL="nano"
fi
model=${2:-${JETSON_MODEL}}

## Jetson model
from=${3:-${FROM}}


## Options for docker build
shift; shift; shift
options="$@"

cd $(dirname "$0")/../$project
echo "Building $IMAGES for project $project and Jetson model $model with FROM=$from and $options ..."

## Sync src from development machine to device
echo "Synching from development machine to build@${model}-one.local for project $project ..."
rsync -rlptza --delete -P src/ build@${model}-one.local:~/$project

## Build Docker image on device
ssh build@${model}-one.local << EOF
  if [ -z "$from" ]; then
    echo "Executing on build@${model}-one.local: docker build -t $project ~/$project $options"
    docker build -t $project ~/$project $options
  else
    echo "Executing on build@${model}-one.local: docker build -t $project ~/$project --build-arg FROM=$from $options"
    docker build -t $project ~/$project --build-arg FROM=$from $options
  fi
EOF

## Tag and possibly push images
for image in $(echo $IMAGES | tr " " "\n")
do
    echo "Tagging as $image for project $project..."
    ssh build@${model}-one.local "docker tag $project $image"
    if $PUSH_IMAGE; then
        echo "Pushing $image for project $project..."
        ssh build@${model}-one.local "docker push $image"
    fi
    # echo "Pulling $image on host ..."
    # docker pull $image
done

echo "Building $IMAGES for project $project done."
