#!/usr/bin/env bash

## Project to build
project=$1

cd $(dirname "$0")/../$project
echo "Building $IMAGES for project $project ..."

## Sync src from development machine to nano
echo "Synching from devlopment machine to nano for project $project ..."
rsync -rlptza --delete -P src/ build@nano-one.local:~/$project

## Build Docker image on nano
ssh build@nano-one.local << EOF
  echo "Building Docker image on nano for project $project ..."
  if [ -z "$2" ]; then
    echo "Not overriding FROM ..."
    docker build -t $project ~/$project
  else
    from=$2
    echo "Using FROM $from as build argument ..."
    docker build -t $project ~/$project --build-arg FROM=$from
  fi
EOF

## Tag and possibly push images
for image in $(echo $IMAGES | tr " " "\n")
do
    echo "Tagging as $image for project $project..."
    ssh build@nano-one.local "docker tag $project $image"
    if $PUSH_IMAGE
    then
        echo "Pushing $image for project $project..."
        ssh build@nano-one.local "docker push $image"
    fi
done
