#!/usr/bin/env bash

## Project to build
project=$1
user=$2
password=$3
cd $(dirname "$0")/../$project

## Publish latests Docker image available found on nano to Docker Hub
ssh build@nano-one.local << EOF
  echo "Executing container structure tests for project $project ..."
  cd $project
  for file in test/*.yaml; do
    container-structure-test test --image $project --verbosity debug --config test/\${file##*/}
  done
EOF
