#!/usr/bin/env bash

## Jetson model
if [[ -z "${JETSON_MODEL}" ]]; then
  JETSON_MODEL="nano"
fi
model=${1:-${JETSON_MODEL}}

echo "Repacking cuda-ml packages on ${model} and creating local repository ..."
ssh build@${model}-one.local << EOF
    echo "Repacking packages for cuda-ml such as CUDNN, TensorRT and python bindings on ${model} ..."
    sudo su
    rm -rf /var/cuda-ml-local-repo || true
    mkdir /var/cuda-ml-local-repo
    cd /var/cuda-ml-local-repo
    dpkg-repack \$(dpkg -l | grep cuda10 | awk '{print \$2}' | tr '\n' ' ')
EOF
