#!/usr/bin/env bash

## Project to build
project=$1
user=$2
password=$3
cd $(dirname "$0")/../$project

## Publish latests Docker image available found on nano to Docker Hub
ssh build@nano-one.local << EOF
  echo "Logging in to Docker Hub as $user ..."
  docker login --username $user --password $password
  echo "Publishing latest image of project $project to Docker Hub as $user/jetson-$project:latest ..."
  docker tag $project $user/jetson-$project:latest
  docker push $user/jetson-$project:latest
EOF
