#!/usr/bin/env bash

## Project to build
project=$1
user=$2
password=$3
cd $(dirname "$0")/../$project

## Jetson model
if [[ -z "${JETSON_MODEL}" ]]; then
  JETSON_MODEL="nano"
fi
model=${4:-${JETSON_MODEL}}

# Publish
echo "Publish latest Docker image available found on ${model} to Docker Hub"
ssh build@${model}-one.local << EOF
  echo "Logging in to Docker Hub as $user ..."
  docker login --username $user --password $password
  echo "Publishing latest image of project $project to Docker Hub as $user/jetson-$model-$project:latest ..."
  docker tag $project $user/jetson-$model-$project:latest
  docker push $user/jetson-$model-$project:latest
EOF
