#!/usr/bin/env bash

echo "Building $IMAGES ..."

## Project to build
project=jupyter

## Sync src to nano
rsync -rlptza --delete -P src/ build@nano-one.local:~/$project

## Build on nano
ssh build@nano-one.local << EOF
  echo "Building $project Docker image ..."
  docker build -t $project ~/$project
EOF

## Tag and possibly push images
for image in $(echo $IMAGES | tr " " "\n")
do
    echo "Tagging as $image ..."
    ssh build@nano-one.local "docker tag $project $image"
    if $PUSH_IMAGE
    then
        echo "Pushing $image ..."
        ssh build@nano-one.local "docker push $image"
    fi
done
