#!/usr/bin/env bash

echo "Building $IMAGES ..."

## Sync src to nano
rsync -rlptza --delete -P src/ build@nano-one.local:~/device-query

## Build on nano
ssh build@nano-one.local << EOF
  echo "Building executable ..."
  cd /usr/local/cuda/samples/1_Utilities/deviceQuery
  sudo make clean
  sudo make
  cp deviceQuery ~/device-query/deviceQuery

  echo "Building Docker image ..."
  docker build -t device_query ~/device-query
EOF

## Tag and possibly push image
for image in $(echo $IMAGES | tr " " "\n")
do
    echo "Tagging with $image ..."
    ssh build@nano-one.local "docker tag device_query $image"
    if $PUSH_IMAGE
    then
        echo "Pushing $image ..."
        ssh build@nano-one.local "docker push $image"
    fi
done
